### ISSUE TITLE
failed semantic-release-with-github-actions

### ISSUE THREAD

**Issue by ajeetvolvo** [zeke/semantic-release-with-github-actions#15]
Hi Zeke, i have followed all the steps given by you but still falling with same error, could you Please have a look on my repo and check if i am missing anything . 

Repo:

https://github.com/ajeetvolvo/release_note_automation

logs:

``` 
lease/npm/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/home/runner/work/release_note_automation/release_note_automation/node_modules/@semantic-release/npm/lib/publish.js:30:5)
    at async validator (/home/runner/work/release_note_automation/release_note_automation/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/release_note_automation/release_note_automation/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/release_note_automation/release_note_automation/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm publish /home/runner/work/release_note_automation/release_note_automation --userconfig /tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc --tag latest --registry https://registry.npmjs.org/',
  command: 'npm publish /home/runner/work/release_note_automation/release_note_automation --userconfig /tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc --tag latest --registry https://registry.npmjs.org/',
  escapedCommand: 'npm publish "/home/runner/work/release_note_automation/release_note_automation" --userconfig "/tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm notice \n' +
    'npm notice 📦  semantic-release-with-github-actions@1.11.0\n' +
    'npm notice === Tarball Contents === \n' +
    'npm notice 466B .github/workflows/semantic.yml\n' +
    'npm notice 0B   README.MD                     \n' +
    'npm notice 303B package.json                  \n' +
    'npm notice 47B  testfile.txt                  \n' +
    'npm notice === Tarball Details === \n' +
    'npm notice name:          semantic-release-with-github-actions           \n' +
    'npm notice version:       1.11.0                                         \n' +
    'npm notice filename:      semantic-release-with-github-actions-1.11.0.tgz\n' +
    'npm notice package size:  607 B                                          \n' +
    'npm notice unpacked size: 816 B                                          \n' +
    'npm notice shasum:        a3135b2f857a0bda7918a10061e7aaf578e667ec       \n' +
    'npm notice integrity:     sha512-YfUpKDNMVS9SK[...]dSuGBGNVBfJig==       \n' +
    'npm notice total files:   4                                              \n' +
    'npm notice \n' +
    'npm ERR! code E403\n' +
    'npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/semantic-release-with-github-actions - You do not have permission to publish "semantic-release-with-github-actions". Are you logged in as the correct user?\n' +
    'npm ERR! 403 In most cases, you or one of your dependencies are requesting\n' +
    'npm ERR! 403 a package version that is forbidden by your security policy, or\n' +
    'npm ERR! 403 on a server you do not have access to.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/runner/.npm/_logs/2021-06-17T06_45_44_648Z-debug.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
}
Error: Command failed with exit code 1: npm publish /home/runner/work/release_note_automation/release_note_automation --userconfig /tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc --tag latest --registry https://registry.npmjs.org/
npm notice 
npm notice 📦  semantic-release-with-github-actions@1.11.0
npm notice === Tarball Contents === 
npm notice 466B .github/workflows/semantic.yml
npm notice 0B   README.MD                     
npm notice 303B package.json                  
npm notice 47B  testfile.txt                  
npm notice === Tarball Details === 
npm notice name:          semantic-release-with-github-actions           
npm notice version:       1.11.0                                         
npm notice filename:      semantic-release-with-github-actions-1.11.0.tgz
npm notice package size:  607 B                                          
npm notice unpacked size: 816 B                                          
npm notice shasum:        a3135b2f857a0bda7918a10061e7aaf578e667ec       
npm notice integrity:     sha512-YfUpKDNMVS9SK[...]dSuGBGNVBfJig==       
npm notice total files:   4                                              
npm notice 
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/semantic-release-with-github-actions - You do not have permission to publish "semantic-release-with-github-actions". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-17T06_45_44_648Z-debug.log
    at makeError (/home/runner/work/release_note_automation/release_note_automation/node_modules/@semantic-release/npm/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/release_note_automation/release_note_automation/node_modules/@semantic-release/npm/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/home/runner/work/release_note_automation/release_note_automation/node_modules/@semantic-release/npm/lib/publish.js:30:5)
    at async validator (/home/runner/work/release_note_automation/release_note_automation/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/release_note_automation/release_note_automation/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/release_note_automation/release_note_automation/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm publish /home/runner/work/release_note_automation/release_note_automation --userconfig /tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc --tag latest --registry https://registry.npmjs.org/',
  command: 'npm publish /home/runner/work/release_note_automation/release_note_automation --userconfig /tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc --tag latest --registry https://registry.npmjs.org/',
  escapedCommand: 'npm publish "/home/runner/work/release_note_automation/release_note_automation" --userconfig "/tmp/7f4d1faa1f2b433bf10e16d5ac1906eb/.npmrc" --tag latest --registry "https://registry.npmjs.org/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm notice \n' +
    'npm notice 📦  semantic-release-with-github-actions@1.11.0\n' +
    'npm notice === Tarball Contents === \n' +
    'npm notice 466B .github/workflows/semantic.yml\n' +
    'npm notice 0B   README.MD                     \n' +
    'npm notice 303B package.json                  \n' +
    'npm notice 47B  testfile.txt                  \n' +
    'npm notice === Tarball Details === \n' +
    'npm notice name:          semantic-release-with-github-actions           \n' +
    'npm notice version:       1.11.0                                         \n' +
    'npm notice filename:      semantic-release-with-github-actions-1.11.0.tgz\n' +
    'npm notice package size:  607 B                                          \n' +
    'npm notice unpacked size: 816 B                                          \n' +
    'npm notice shasum:        a3135b2f857a0bda7918a10061e7aaf578e667ec       \n' +
    'npm notice integrity:     sha512-YfUpKDNMVS9SK[...]dSuGBGNVBfJig==       \n' +
    'npm notice total files:   4                                              \n' +
    'npm notice \n' +
    'npm ERR! code E403\n' +
    'npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/semantic-release-with-github-actions - You do not have permission to publish "semantic-release-with-github-actions". Are you logged in as the correct user?\n' +
    'npm ERR! 403 In most cases, you or one of your dependencies are requesting\n' +
    'npm ERR! 403 a package version that is forbidden by your security policy, or\n' +
    'npm ERR! 403 on a server you do not have access to.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +

**Comment by mdrijwan** [comment]
@ajeetvolvo hey man, this is because of your npm registry. make sure you have setup the right npm token with the right publishing access.
